development:
  adapter: any_cable

test:
  adapter: async

production:
  adapter: any_cable
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: actioncable_app_production
